#
# Auto generated Makefile.config for platform haskell-platform-2012.2.0.0
#
GHC_VERSION = 7.4.1
PACKAGE_CONSTRAINTS = cgi==3001.1.7.4 \
                      fgl==5.4.2.4 \
                      GLUT==2.1.2.1 \
                      haskell-src==1.0.1.5 \
                      html==1.0.1.2 \
                      HTTP==4000.2.3 \
                      HUnit==1.2.4.2 \
                      mtl==2.1.1 \
                      network==2.3.0.13 \
                      OpenGL==2.2.3.1 \
                      parallel==3.2.0.2 \
                      parsec==3.1.2 \
                      QuickCheck==2.4.2 \
                      random==1.0.1.1 \
                      regex-base==0.93.2 \
                      regex-compat==0.95.1 \
                      regex-posix==0.95.1 \
                      stm==2.3 \
                      syb==0.3.6.1 \
                      text==0.11.2.0 \
                      transformers==0.3.0.0 \
                      xhtml==3000.2.1 \
                      zlib==0.5.3.3
