# Do not edit this file unless you know what you are doing.

include Makefile.configure # Read in configuration

# The targets provided by this make file are the following:

.PHONY: install # Installs all the packages.
.PHONY: clean   # removes all the packages and cleans up the dirs.
.PHONY: tests   # Runs the tests. Assumes that install is already done.
.PHONY: echo-variables        # Shows make variables. mainly for debugging
.PHONY: travis-before-install # Sets up the travis environment.
.PHONY: travis-cabal-config   # Sets up the travis cabal config file
.PHONY: hlint   # runs hlint on the sources
.PHONY: src-tarball # Creates the source tarballs in the respective directories.
.PHONY: scripts     # builds the scripts in the scripts directory
.PHONY: tags        # create the ctags and etags files
#
# For each package we have a target with the same name and a target
# with the suffix clean. The former builds the package and the latter
# cleans it up. The Makefile.configure should set the variable
# PACKAGES variable and add rules to capture dependencies between the
# package targets (see the comments in Makefile.configure). The
# cleaning targets are auto generated from them.
#


PACKAGE_CLEAN=$(addsuffix -clean, ${PACKAGES})

.PHONY: ${PACKAGES} # There is a target for each packages. You set this
                    # variable in the Makefile.configure.
.PHONY: ${PACKAGE_CLEAN}


# External variables that govern the building process.


TEST_PATH=dist/build/tests/tests # path to the tests in any package.

export PACKAGES

#
# Sets up the cabal config. The directory platform contains the cabal
# config file to use for each platform. Typically you need to put the
# package constraints there. The platform/default.cabal.conf contains
# the default config to use.
#

ROOTDIR=$(abspath .)

# Include the platform specific configurarions from the platform make
# file.

ifdef HASKELL_PLATFORM
include ${ROOTDIR}/platform/${HASKELL_PLATFORM}/Makefile.configure
endif

# In travis builds you can set particular versions of the compiler. In
# particular, the platform specific Makefile.configure should set the
# appropriate GHC version.

ifdef GHC_VERSION

GHC_PKG=ghc-${GHC_VERSION}
PATH:=/opt/ghc/${GHC_VERSION}/bin:${PATH}

else

GHC_PKG=ghc

endif


ifdef CABAL_VERSION

CABAL_PKG=cabal-install-${CABAL_VERSION}
CABAL=cabal-${CABAL_VERSION} ${CABAL_OPT}

else

CABAL_PKG=cabal-install
CABAL=cabal ${CABAL_OPTS}

endif

# Setting the cabal install DEPENDENCIES
DEPENDENCIES=$(foreach cons, ${PACKAGE_CONSTRAINTS} \
			     ${ADDITIONAL_CONSTRAINTS}\
	,--constraint='${cons}' )

# Package tarballs. We install directly from the tarballs
RAAZ_TAR_GZ=$(foreach pkg, ${PACKAGES}, \
	$(wildcard ${ROOTDIR}/${pkg}/dist/*.tar.gz))

CABAL_INSTALL= ${CABAL} install ${DEPENDENCIES}

scripts:
	make -C scripts all

echo-variables:
	@echo Makefile variables.
	@echo -e '\t'CABAL_VERSION=${CABAL_VERSION}
	@echo -e '\t'CABAL_CONFIG=${CABAL_CONFIG}
	@echo -e '\t'GHC_VERSION=${GHC_VERSION}
	@echo -e '\t'HASKELL_PLATFORM=${HASKELL_PLATFORM}

	@echo -e '\t'ghc,cabal: ${GHC_PKG} ${CABAL_PKG}
	@echo -e '\t'DEPENDENCIES: ${DEPENDENCIES}
	@echo -e '\t'RAAZ_TAR_GZ: ${RAAZ_TAR_GZ}

install: src-tarball
	${CABAL_INSTALL} --only-dependencies \
		${RAAZ_TAR_GZ}
	${CABAL_INSTALL} --enable-tests --enable-benchmarks \
		 --enable-documentation \
		${RAAZ_TAR_GZ}
	@echo User packages installed
	ghc-pkg list --user

tests:
	$(foreach pkg, ${PACKAGES},\
		cd ${pkg};\
		${CABAL} test;\
		cd ..;\
		)

src-tarball:
	cd raaz-core; \
	   ${CABAL_INSTALL} --only-dependencies; \
	   ${CABAL} configure;\
	   cd ..
	$(foreach pkg, ${PACKAGES},\
		  cd ${pkg};\
		  ${CABAL} sdist;\
		  cd ..;\
		)


clean:   ${PACKAGE_CLEAN}

${PACKAGE_CLEAN}:
	cd $(patsubst %-clean,%,$@);\
	./Setup.lhs clean;\
	cd ..
	-ghc-pkg unregister  $(patsubst %-clean,%,$@) --force

#
#  Travis platform setup
#

travis-before-install:
	@echo System: `uname -a`
	sudo add-apt-repository -y ppa:hvr/ghc
	sudo apt-get update
	sudo apt-get install ${CABAL_PKG} ${GHC_PKG} happy haddock
	${CABAL} update

#
#  Stuff that checks the coding style
#

hlint:
	hlint ${PACKAGES}

tags:
	hasktags -b -S".hs,.lhs,hsc" .
