# Do not edit this file unless you know what you are doing.

include Makefile.configure

PACKAGE_CLEAN=$(foreach pkg, ${PACKAGES}, ${pkg}-clean)
TEST_PATH=dist/build/tests/tests

.PHONY: install clean ${PACKAGES} ${PACKAGES_UNREGISTER}

install: ${PACKAGES} raaz
clean:   ${PACKAGE_CLEAN}

${PACKAGES}:
	cd $@;\
	cabal install ${INSTALL_OPTS}

${PACKAGE_CLEAN}:
	cd $(patsubst %-clean,%,$@);\
	./Setup.lhs clean;\
	cd ..
	-ghc-pkg unregister  $(patsubst %-clean,%,$@) --force

.PHONY: travis-install travis-tests

.PHONY: fast-forward fast-forward-all merge release


travis-install:
	make install INSTALL_OPTS='-O0 --enable-documentation --enable-tests'

travis-tests:
	$(foreach pkg, ${PACKAGES},\
		cd ${pkg};\
		cabal test;\
		cd ..;\
		)
