#
# Auto generated Makefile.config for platform haskell-platform-2012.4.0.0
#
GHC_VERSION = 7.4.2
PACKAGE_CONSTRAINTS = async==2.0.1.3 \
                      cgi==3001.1.7.4 \
                      fgl==5.4.2.4 \
                      GLUT==2.1.2.1 \
                      haskell-src==1.0.1.5 \
                      html==1.0.1.2 \
                      HTTP==4000.2.5 \
                      HUnit==1.2.5.1 \
                      mtl==2.1.2 \
                      network==2.3.1.0 \
                      OpenGL==2.2.3.1 \
                      parallel==3.2.0.3 \
                      parsec==3.1.3 \
                      QuickCheck==2.5.1.1 \
                      random==1.0.1.1 \
                      regex-base==0.93.2 \
                      regex-compat==0.95.1 \
                      regex-posix==0.95.2 \
                      split==0.2.1.1 \
                      stm==2.4 \
                      syb==0.3.7 \
                      text==0.11.2.3 \
                      transformers==0.3.0.0 \
                      vector==0.10.0.1 \
                      xhtml==3000.2.1 \
                      zlib==0.5.4.0 \
                      primitive==0.5.0.1
