#
# Auto generated Makefile.config for platform haskell-platform-2013.2.0.0
#
GHC_VERSION = 7.6.3
PACKAGE_CONSTRAINTS = async==2.0.1.4 \
                      attoparsec==0.10.4.0 \
                      case-insensitive==1.0.0.1 \
                      cgi==3001.1.7.5 \
                      fgl==5.4.2.4 \
                      GLUT==2.4.0.0 \
                      GLURaw==1.3.0.0 \
                      haskell-src==1.0.1.5 \
                      hashable==1.1.2.5 \
                      html==1.0.1.2 \
                      HTTP==4000.2.8 \
                      HUnit==1.2.5.2 \
                      mtl==2.1.2 \
                      network==2.4.1.2 \
                      OpenGL==2.8.0.0 \
                      OpenGLRaw==1.3.0.0 \
                      parallel==3.2.0.3 \
                      parsec==3.1.3 \
                      QuickCheck==2.6 \
                      random==1.0.1.1 \
                      regex-base==0.93.2 \
                      regex-compat==0.95.1 \
                      regex-posix==0.95.2 \
                      split==0.2.2 \
                      stm==2.4.2 \
                      syb==0.4.0 \
                      text==0.11.3.1 \
                      transformers==0.3.0.0 \
                      unordered-containers==0.2.3.0 \
                      vector==0.10.0.1 \
                      xhtml==3000.2.1 \
                      zlib==0.5.4.1 \
                      primitive==0.5.0.1
